[project]
name = "evergreen"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.7",
    "jupyterlab-widgets>=3.0.15",
    "matplotlib>=3.10.8",
    "pandas>=2.2.3",
    "tqdm>=4.67.1",
]
